### ISSUE TITLE
Example in README for repeated value causes a panic

### ISSUE THREAD

**Issue by bengadbois** [alecthomas/kingpin#164]
Running the following program:

test.go:
```
package main

import (
    "fmt"
    kingpin "gopkg.in/alecthomas/kingpin.v2"
    "net/http"
    "strings"
)

var (
    test        = kingpin.Command("test", "")
    testHeaders = HTTPHeader(test.Flag("header", "Add arbitrary header line, eg. 'Accept-Encoding: gzip'").Short('H'))
)

func main() {
    switch kingpin.Parse() {
    case "test":
        kingpin.FatalIfError(runTest(), "test failed")
    }
}
func runTest() error {
    fmt.Println(*testHeaders)
    return nil
}

type HTTPHeaderValue http.Header

func (h *HTTPHeaderValue) Set(value string) error {
    parts := strings.SplitN(value, ":", 2)
    if len(parts) != 2 {
        return fmt.Errorf("expected HEADER:VALUE got '%s'", value)
    }
    (*http.Header)(h).Add(parts[0], parts[1])
    return nil
}

func (h *HTTPHeaderValue) String() string {
    return ""
}

func HTTPHeader(s kingpin.Settings) (target *http.Header) {
    target = new(http.Header)
    s.SetValue((*HTTPHeaderValue)(target))
    return
}
```

Running ```./bin/test test -H key:val```:
```
panic: assignment to entry in nil map

goroutine 1 [running]:
panic(0x6cffe0, 0xc420077450)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
net/textproto.MIMEHeader.Add(0x0, 0x7fff58053d49, 0x3, 0x7fff58053d4d, 0x3)
        /usr/local/go/src/net/textproto/header.go:15 +0x12f
net/http.Header.Add(0x0, 0x7fff58053d49, 0x3, 0x7fff58053d4d, 0x3)
        /usr/local/go/src/net/http/header.go:24 +0x53
main.(*HTTPHeaderValue).Set(0xc4200840d8, 0x7fff58053d49, 0x7, 0x6, 0x8b6380)
        /home/x/go/src/test/test.go:33 +0x9e
test/vendor/gopkg.in/alecthomas/kingpin%2ev2.(*Application).setValues(0xc4200c8000, 0xc42009c1b0, 0x0, 0x0, 0xc42009c1b0, 0x0, 0x0)
        /home/x/go/src/test/vendor/gopkg.in/alecthomas/kingpin.v2/app.go:485 +0x3c8
test/vendor/gopkg.in/alecthomas/kingpin%2ev2.(*Application).Parse(0xc4200c8000, 0xc420074110, 0x3, 0x3, 0x40541b, 0xc420072058, 0x0, 0xc4200c8780)
        /home/x/go/src/test/vendor/gopkg.in/alecthomas/kingpin.v2/app.go:199 +0xdb
test/vendor/gopkg.in/alecthomas/kingpin%2ev2.Parse(0x0, 0x0)
        /home/x/go/src/test/vendor/gopkg.in/alecthomas/kingpin.v2/global.go:37 +0x7e
main.main()
        /home/x/go/src/test/test.go:16 +0x26
```

Perhaps I'm not using it correctly, but this is what I gathered from the README

If the flag isn't used, it's fine

**Comment by alecthomas** [comment]
Should be:

```go
func HTTPHeader(s kingpin.Settings) (target *http.Header) {
    target = &http.Header{}
    s.SetValue((*HTTPHeaderValue)(target))
    return
}
```

Updated the README
